services:
  # BASE DE DATOS (Contenedor de MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      # AQUÍ: Ponemos el nombre de tu base de datos actual
      MYSQL_DATABASE: hotel_db
      # AQUÍ: Ponemos tu contraseña actual
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - "3306:3306"

  # BACKEND JAVA
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      # IMPORTANTE: En Docker, 'localhost' pasa a ser el nombre del servicio 'db'
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hotel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  # FRONTEND NEXT.JS
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend