services:
  # BASE DE DATOS MYSQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: altairis_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  # BACKEND JAVA
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/altairis_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - db

  # FRONTEND NEXT.JS
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend